CC=gcc
#CFLAGS=-std=gnu99 -Wall -g -pg
#CFLAGS=-std=gnu99 -Wall -g -O3 -mtune=corei7-avx -mavx -march=corei7-avx
CFLAGS=-std=gnu99 -Wall -g -DDEBUG

all: quali-d

quali-d: quali-d.c

.PHONY: clean
clean:
	rm -f quali-d
